### ISSUE TITLE
Search returns generic error

### ISSUE THREAD

**Issue by Koxzi95** [OfficeDev/microsoft-teams-apps-expertfinder#5]
After following the deployment guide all other functions of the app work except for search. It returns a generic error as below. 
![search](https://user-images.githubusercontent.com/6239399/76461238-6f05f000-63d7-11ea-8e4d-1ca31f4e59c7.jpg)

No specific errors & app insights does not seem to be configured with the deployment.

**Comment by AyshwaryaRamakrishnan** [comment]
I am experiencing the same issue as @Koxzi95 after deploying it on our tenant. Search is not working. Any fix available? 
![image](https://user-images.githubusercontent.com/12132097/79326202-fe844e80-7f01-11ea-974d-0bce0a64e030.png)

**Comment by abbodh** [comment]
Looks like the application instrumentation key name is mis-matched in ARM deployment templates which is causing the issue. We are working on a fix and will update it ASAP. 

As a workaround, can you try adding AppInsightsInstrumentationKey in Configuration settings and provide the value of app insights created during deployment. So for e.g. your base resource name while creating the deployment is "Contoso-Expert-Finder" then application insight resource name would be "Contoso-Expert-Finder" as well.

**Comment by aosolis** [comment]
The issue fixed by @abbodh PR #9 is in PR #10

**Comment by aqyx** [comment]
This issue is still present, experienced the same problem when deploying for a customer yesterday. API app reg permissions have been double-checked and are correct as per the deployment guide.
